services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50001:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build:
      context: ./make-decision-helper-back
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:3306/make-decision-helper
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis
      - mongodb

  frontend:
    build:
      context: ./make-decision-helper-front
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    environment:
      - ${MONGO_USER}=root
      - ${MONGO_PASSWORD}=1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  mongodb_data:
  redis_data:
  jenkins_home: