version: '3.8'

services:
  backend:
    image: make-decision-helper-backend:green
    container_name: make-decision-helper-backend-green
    build:
      context: ../make-decision-helper-back
      dockerfile: Dockerfile
    env_file:
      - .env.green
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - app-network

  frontend:
    image: make-decision-helper-frontend:green
    container_name: make-decision-helper-frontend-green
    build:
      context: ../make-decision-helper-front
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  nginx:
    image: make-decision-helper-nginx:green
    container_name: make-decision-helper-nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: true