version: '3.8'

services:
  backend:
    image: make-decision-helper-backend:blue
    container_name: make-decision-helper-backend-blue
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=blue
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    restart: always

  frontend:
    image: make-decision-helper-frontend:blue
    container_name: make-decision-helper-frontend-blue
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  nginx:
    image: make-decision-helper-nginx
    container_name: make-decision-helper-nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always
