version: '3.8'

services:
  backend:
    image: make-decision-helper-backend:blue
    container_name: make-decision-helper-backend-blue
    build:
      context: ../make-decision-helper-back
      dockerfile: Dockerfile
    env_file:
      - .env.blue
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - app-network

  frontend:
    image: make-decision-helper-frontend:blue
    container_name: make-decision-helper-frontend-blue
    build:
      context: ../make-decision-helper-front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  nginx:
    image: make-decision-helper-nginx:blue
    container_name: make-decision-helper-nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
    restart: always
    networks:
      - app-network